---
# copy files needed to reconfigure and manage archive

# Create bbric archive files directory.
- name: Create bbric archive files directory.
  file:
    path: "{{ bbric_archive_opt }}"
    state: directory
    mode: 0660
    owner: root
    group: root

# Copy patches into bbric archive files directory.
- name: Copy patches into bbric archive files directory.
  copy:
    src: "{{ role_path }}/files/patches"
    dest: "{{ bbric_archive_opt }}/"
- name: Find patches after copy.
  find:
    path: "{{ bbric_archive_opt }}/patches"
    patterns: "*.patch"
  register: patch_copies 
- name: Check patches present after copy.
  file:
    path: "{{ item.path }}"
    state: file
  with_items: "{{ patch_copies.files }}"

# Deploy miniclient.pl template into bbric archive files directory.
- name: Create miniclient directory into bbric archive files directory. 
  file: 
    path: "{{ bbric_archive_opt}}/miniclient"
    state: directory
    mode: 0660
    owner: root
    group: root

- name: Copy miniclient.pl into bbric archive files directory.
  template:
    src: templates/miniclient/miniclient.pl.j2
    dest: "{{ bbric_archive_opt }}/miniclient/miniclient.pl"
    owner: root
    group: root
    mode: '0750'    
  
