---
# tasks file for ansible-role-bbric-archive

# Include OS-specific variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Install dependencies.
- name: Define archive dependency debian packages.
  set_fact:
    deps_packages: "{{ __deps_packages | list }}"
  when: deps_packages is not defined

- name: Define archive dependency perl modules.
  set_fact:
    perl_modules: "{{ __perl_modules | list }}"
  when: perl_modules is not defined

# Setup/install tasks.
- include: "setup-deps-{{ ansible_os_family }}.yml" 
  static: no

# Clean setup tasks.
- include: "clean-setup-{{ ansible_os_family }}.yml"
  static: no

# post-install config.
- include: "post-setup-deps-install-config-{{ ansible_os_family }}.yml"
  static: no

# copy files.
- include: "copy-files.yml"
  static: no

# download and reconfigure BBRIC Archive.
- include: "download-reconfigure-bbric-archive-{{ ansible_os_family }}.yml"
  static: no

# apache configuration.
- include: "apache-config-{{ ansible_os_family }}.yml"
  static: no

# setup miniclient cron job.
- include: "cron-miniclient-{{ ansible_os_family }}.yml"
  static: no

# archive database configuration.
- include: "archive-database-config-{{ ansible_os_family }}.yml"
  static: no

# init archive sequence index.
- include: "init-archive-elastic-seq-index-{{ ansible_os_family }}.yml"
  static: no

# setup archive storage directories.
- include: "setup-archive-storage-directories-{{ ansible_os_family }}.yml"
  static: no

# create symlink to archive_root_dir
- include: "create-symlink-archive-root-dir-{{ ansible_os_family }}.yml"
  static: no

# ensure permissions on archive root directory
- include: "ensure-permissions-archive-root-dir-{{ ansible_os_family }}.yml"
  static: no

# restart services
- include: "restart-services-{{ ansible_os_family }}.yml"
  static: no
